* Load other version virtualenv if no lib for current python. * Virtualenv installation can use PYPI mirrors.

diff --git a/debian/pysvnmanager-deploy-virt.postinst b/debian/pysvnmanager-deploy-virt.postinst
--- a/debian/pysvnmanager-deploy-virt.postinst
+++ b/debian/pysvnmanager-deploy-virt.postinst
@@ -36,10 +36,10 @@ if [ -z "$2" ]; then
 fi
 
 if [ ! -f /opt/pysvnmanager/virtualenv/bin/activate ]; then
-    make -C /opt/pysvnmanager/virtualenv all
+    make -C /opt/pysvnmanager/virtualenv all || echo "** Install virtualenv failed **"
 elif dpkg --compare-versions "$2" lt "1:0.5.2r165-53" ; then
     ## version 1:0.5.2r165-52: + simplejson.
-    make -C /opt/pysvnmanager/virtualenv all
+    make -C /opt/pysvnmanager/virtualenv all || echo "** Install virtualenv failed **"
 fi
 
 if [ -z "$2" ] && [ ! -d $SITE ]; then
